# github/mohamadmorady412

In [ ]:
! pip install kaggle

In [ ]:
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
! kaggle datasets download -d waseemnagahhenes/lung-cancer-dataset-iq-othnccd

In [ ]:
from zipfile import ZipFile

zip_file_name = "/content/lung-cancer-dataset-iq-othnccd.zip"

with ZipFile(zip_file_name, 'r') as zip_ref:

    zip_ref.printdir()
    zip_ref.extractall('/content/Lung-data2')

    print("Done!")

In [ ]:
import cv2
i = cv2.imread("/content/Lung-data2/Data/The IQ-OTHNCCD lung cancer dataset/Bengin cases/Bengin case (1).jpg")
i

In [ ]:
# clean after

import os

def conter(directory_path):
  f = 0
  for item in os.listdir(directory_path):
    if os.path.isfile(os.path.join(directory_path, item)):
      f += 1
  print(f'number of file in {directory_path}: {f}')

l = [
    '/content/Lung-data2/Data/The IQ-OTHNCCD lung cancer dataset/Bengin cases',
     '/content/Lung-data2/Data/The IQ-OTHNCCD lung cancer dataset/Malignant cases',
     '/content/Lung-data2/Data/The IQ-OTHNCCD lung cancer dataset/Normal cases'
     ]

for i in l:
  conter(i)

In [ ]:
%matplotlib inline
from numpy import save
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from keras.preprocessing.image import ImageDataGenerator
from keras.applications import vgg16

In [ ]:
generaitor = ImageDataGenerator(rescale=1./255)

In [ ]:
gen = generaitor.flow_from_directory('/content/Lung-data2/Data/The IQ-OTHNCCD lung cancer dataset')

In [ ]:
vgg_model = vgg16.VGG16(weights='imagenet', include_top=False, pooling='avg')

In [ ]:
def extract_features(model, image):
  features = model.predict(image)
  features = features.flatten()
  return features

In [ ]:
features = extract_features(vgg_model, gen)

In [ ]:
save('/content/drive/MyDrive/gogoly.npy', features)

In [ ]:
def continue_toshape(data, data_size: int, num_features: int) -> np.array:
    if data_size % num_features != 0:
      s = f'data size {data_size} and num feachrs {num_features}: {data_size} / {num_features} == {data_size / num_features}'
      raise ValueError(s)

    target_array = np.zeros((data_size // num_features, num_features))

    partition = num_features
    row_conter = 0
    for i in range(0, data_size, num_features):
      target_array[row_conter] = data[i:partition]

      row_conter += 1 ; partition += num_features
    return target_array

In [ ]:
kmeans = KMeans(3, random_state=0)
kmeans.fit(X)
labels = kmeans.labels_

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
y = np.zeros(2073)
y[:120] = 1
y[120:1339+120] = 2
y[1339+120:] = 3

cm = confusion_matrix(labels, y)
print(cm)

[[  0  16 160  81]
 [  0  68 694 289]
 [  0  36 485 244]
 [  0   0   0   0]]
